=== examisfun/arm-history/src/main/resources/queries/Synergy-Queries-Schema-1.1.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
  <xs:element name="queries">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="query" maxOccurs="unbounded" minOccurs="0"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="query">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="description"/>
        <xs:element ref="params"/>
        <xs:element ref="dialects" maxOccurs="1"/>
      </xs:sequence>
      <xs:attribute name="createdBy" use="required" type="xs:string"/>
      <xs:attribute name="createdOn" use="required" type="xs:date"/>
      <xs:attribute name="id" use="required" type="xs:token"/>
      <xs:attribute name="modifiedBy" use="optional" type="xs:string"/>
      <xs:attribute name="modifiedOn" use="optional" type="xs:date"/>
      <xs:attribute name="implementedBy" use="optional" type="xs:string"/>
      <xs:attribute name="implementedOn" use="optional" type="xs:date"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="description" type="xs:string"/>
  <xs:element name="params">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="param" maxOccurs="unbounded" minOccurs="0"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="param">
    <xs:complexType mixed="true">
      <xs:attribute name="name" use="required" type="xs:string"/>
      <xs:attribute name="type" use="optional" type="xs:token"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="dialects">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="language" maxOccurs="3"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="language">
    <xs:complexType mixed="true">
      <xs:attribute name="name" use="required">
        <xs:simpleType>
          <xs:restriction base="xs:token">
            <xs:enumeration value="mssql"/>
            <xs:enumeration value="oracle"/>
            <xs:enumeration value="mysql"/>
            <xs:enumeration value="postgre"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:attribute>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== examisfun/arm-history/src/main/resources/queries/arm_history_queries.xml
<?xml version="1.0" encoding="utf-8"?>
<queries xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
		 xsi:noNamespaceSchemaLocation="Synergy-Queries-Schema-1.1.xsd">

	<query id="loadQuestions" createdBy="David Voskanyan" implementedBy="David Voskanyan"
		   createdOn="2017-06-10">
		<dialects>
			<language name="postgre">
				<![CDATA[
				SELECT  Questions.id,
						Questions.question,
        				Questions.type,
        				SimpleAnswers.id AS answerId,
        				SimpleAnswers.answer,
        				SimpleAnswers.option,
        				SimpleAnswers.isTrueAnswer
				FROM Questions JOIN SimpleAnswers ON Questions.id = SimpleAnswers.questionId
					]]>
			</language>
		</dialects>
	</query>

	<query id="insertQuestions" createdBy="Gevorg Minasyan" implementedBy="Gevorg Minasyan"
		   createdOn="2017-06-10">
		<dialects>
			<language name="postgre">
				<![CDATA[
				INSERT INTO Questions(question, type) VALUES (?, ?)
					]]>
			</language>
		</dialects>
	</query>

	<query id="insertAnswers" createdBy="Gevorg Minasyan" implementedBy="Gevorg Minasyan"
		   createdOn="2017-06-10">
		<dialects>
			<language name="postgre">
				<![CDATA[
				INSERT INTO SimpleAnswers(questionId, answer, option, isTrueAnswer) VALUES (:questionId, :answer, :option, :trueAnswer)
					]]>
			</language>
		</dialects>
	</query>

	<query id="loadSubjects" createdBy="Gevorg Minasyan" implementedBy="Gevorg Minasyan"
		   createdOn="2017-06-11">
		<dialects>
			<language name="postgre">
				<![CDATA[
				SELECT subjectId, name
				FROM subjects
					]]>
			</language>
		</dialects>
	</query>


	<query id="loadHeadersBySubjectId" createdBy="Gevorg Minasyan" implementedBy="Gevorg Minasyan"
		   createdOn="2017-06-12">
		<dialects>
			<language name="postgre">
				<![CDATA[
				SELECT headerId, subjectId, name
				FROM headers
				WHERE subjectId = :subjectId
					]]>
			</language>
		</dialects>
	</query>

</queries>
